/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class GPIO_Sun8i_GPIOCtrl */

#ifndef _Included_GPIO_Sun8i_GPIOCtrl
#define _Included_GPIO_Sun8i_GPIOCtrl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GPIO_Sun8i_GPIOCtrl
 * Method:    gpio_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_GPIO_Sun8i_GPIOCtrl_gpio_1init
  (JNIEnv *, jclass);

/*
 * Class:     GPIO_Sun8i_GPIOCtrl
 * Method:    gpio_setcfg
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_GPIO_Sun8i_GPIOCtrl_gpio_1setcfg
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     GPIO_Sun8i_GPIOCtrl
 * Method:    gpio_getcfg
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_GPIO_Sun8i_GPIOCtrl_gpio_1getcfg
  (JNIEnv *, jclass, jint);

/*
 * Class:     GPIO_Sun8i_GPIOCtrl
 * Method:    gpio_output
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_GPIO_Sun8i_GPIOCtrl_gpio_1output
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     GPIO_Sun8i_GPIOCtrl
 * Method:    gpio_pullup
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_GPIO_Sun8i_GPIOCtrl_gpio_1pullup
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     GPIO_Sun8i_GPIOCtrl
 * Method:    gpio_input
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_GPIO_Sun8i_GPIOCtrl_gpio_1input
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
